import { Global, ThemeProvider } from '@emotion/react';
import {
  Hydrate,
  QueryClient,
  QueryClientProvider,
} from '@tanstack/react-query';
import gtag from 'lib/gtag';
import type { AppProps } from 'next/app';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import { useRouter } from 'next/router';
import Script from 'next/script';
import { useEffect, useState } from 'react';
import { global } from 'styles/globals';
import theme from 'styles/theme';

const Layout = dynamic(() => import('components/layout'));

const App = ({ Component, pageProps }: AppProps) => {
  const [hydrated, setHydrated] = useState<boolean>(false);

  const router = useRouter();
  const [queryClient] = useState(() => new QueryClient());

  // GA 조회수 측정
  useEffect(() => {
    const handleRouteChange = (url: URL) => {
      gtag.pageview(url);
    };
    router.events.on('routeChangeComplete', handleRouteChange);
    router.events.on('hashChangeComplete', handleRouteChange);
    return () => {
      router.events.off('routeChangeComplete', handleRouteChange);
      router.events.off('hashChangeComplete', handleRouteChange);
    };
  }, [router.events]);

  useEffect(() => {
    setHydrated(true);
  }, []);

  return (
    <>
      <html lang="ko">
        <Head>
          <title>cassette</title>
          <meta name="theme-color" content="#242729" />
          <meta name="description" content="Generated by create next app" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no"
          />
          <meta property="og:title" content="2023 Voice Tape" />
          <meta property="og:image" content="/ogImage.png" />
          <meta property="og:url" content="https://www.12playlist.com" />
          <meta
            property="og:description"
            content="평소 전하지 못했던 마음을
목소리로 담아보내요. "
          />
          <link rel="manifest" href="/manifest.json" />
          <link
            rel="preload"
            as="image"
            href="../../assets/backgroundImg.svg"
          />
          <link
            rel="preload"
            as="font"
            type="font/woff"
            crossOrigin="anonymous"
            href="https://cdn.jsdelivr.net/gh/Project-Noonnu/noonfonts_2107@1.1/Pretendard-Regular.woff"
          />
          <link
            rel="preload"
            as="font"
            type="font/woff2"
            crossOrigin="anonymous"
            href="https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_11-01@1.0/Ycomputer-Regular.woff2"
          />
          <link rel="preconnect" href="https://www.googletagmanager.com" />
          <link rel="preconnect" href="https://www.google-analytics.com" />
          <link
            href="../../favicons/favicon-16x16.png"
            rel="icon"
            type="image/png"
            sizes="16x16"
          />
          <link
            href="../../favicons/favicon-32x32.png"
            rel="icon"
            type="image/png"
            sizes="32x32"
          />
          <link rel="apple-touch-icon" href="favicons/apple-icon.png"></link>
          <meta name="msapplication-TileColor" content="#242729"></meta>
        </Head>
      </html>
      <Script
        strategy="afterInteractive"
        src={`https://www.googletagmanager.com/gtag/js?id=${gtag.GA_TRACKING_ID}`}
      />
      <Script
        id="gtag-init"
        strategy="afterInteractive"
        dangerouslySetInnerHTML={{
          __html: `
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${gtag.GA_TRACKING_ID}', {
              page_path: window.location.pathname,
            });
          `,
        }}
      />
      <QueryClientProvider client={queryClient}>
        <Hydrate state={pageProps.dehydratedState}>
          {hydrated && (
            <ThemeProvider theme={theme}>
              <Global styles={global} />
              <Layout>
                <Component {...pageProps} />
              </Layout>
              <div id="modal" />
            </ThemeProvider>
          )}
        </Hydrate>
      </QueryClientProvider>
    </>
  );
};

export default App;
