import { Global, ThemeProvider } from '@emotion/react';
import Layout from 'components/layout';
import ReactQueryWrapper from 'lib/reactQueryWrapper';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import { global } from 'styles/globals';
import theme from 'styles/theme';

const App = ({ Component, pageProps }: AppProps) => {
  return (
    <>
      <Head>
        <title>cassette</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.json" />
      </Head>
      <ReactQueryWrapper>
        <ThemeProvider theme={theme}>
          <Global styles={global} />
          <Layout>
            <Component {...pageProps} />
          </Layout>
          <div id="modal" />
        </ThemeProvider>
      </ReactQueryWrapper>
    </>
  );
};

export default App;
